const endpoints = {
  auth: {
    login: '/auth/login',
    refresh: '/auth/refresh',
    logout: '/auth/logout',
    me: '/auth/me',
  },
  admin: {
    users: '/admin/users',
    user: (id) => `/admin/users/${id}`,
    toggleActive: (id) => `/admin/users/${id}/toggle-active`,
    avatar: (id) => `/admin/users/${id}/avatar`,
    lecturers: '/admin/lecturers',
    courses: '/admin/courses',
    course: (id) => `/admin/courses/${id}`,
    units: '/admin/units',
    unit: (id) => `/admin/units/${id}`,
    assignLecturer: '/admin/assign-lecturer',
    assignCourseLecturer: '/admin/assign-course-lecturer',
    enrollStudent: '/admin/enroll-student',
    semesters: '/admin/semesters',
    semester: (id) => `/admin/semesters/${id}`,
    auditLogs: '/admin/audit-logs',
    salaries: '/admin/salaries',
    salary: (id) => `/admin/salaries/${id}`,
    markSalaryPaid: (id) => `/admin/salaries/${id}/mark-paid`,
    lecturerSalaries: (lecturerId) => `/admin/salaries/lecturer/${lecturerId}`,
  },
  student: {
    profile: '/student/profile',
    currentUnits: '/student/current-units',
    currentSemester: '/student/current-semester',
    transcript: '/student/transcript',
    transcriptDownload: '/student/transcript/download',
    feesBalance: '/student/fees/balance',
    payments: '/student/fees/payments',
    receipts: '/student/fees/receipts',
    receiptDownload: (id) => `/student/fees/receipts/${id}/download`,
  },
  lecturer: {
    profile: '/lecturer/profile',
    courses: '/lecturer/courses',
    courseStudents: (id) => `/lecturer/courses/${id}/students`,
    courseResults: (id) => `/lecturer/courses/${id}/results`,
    salary: '/lecturer/salary',
  },
  finance: {
    mpesaCallback: '/finance/payments/mpesa-callback',
    studentFees: (id) => `/finance/students/${id}/fees`,
    studentPayments: (id) => `/finance/students/${id}/payments`,
    manualPayment: (id) => `/finance/students/${id}/payments/manual`,
    mpesaPayment: (id) => `/finance/students/${id}/payments/mpesa-stk`,
    studentInvoices: (id) => `/finance/students/${id}/invoices`,
    createInvoice: (id) => `/finance/students/${id}/invoices`,
    financialReport: (id) => `/finance/reports/student/${id}`,
    receiptDownload: (id) => `/finance/receipts/${id}/download`,
    helbLoans: (id) => `/finance/students/${id}/helb`,
    payments: '/finance/payments',
    payment: (id) => `/finance/payments/${id}`,
    salaries: '/finance/salaries',
    salary: (id) => `/finance/salaries/${id}`,
    markSalaryPaid: (id) => `/finance/salaries/${id}/mark-paid`,
  },
};

export default endpoints;
